name: Build

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build android package
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Android
        run: |
          mkdir -p build/app/outputs/flutter-apk
          touch build/app/outputs/flutter-apk/app-release.apk

      - name: Collect Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MobileNebula.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5

  release:
    needs: [build]

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEXT_TAG="v$(gh release view --json tagName --jq '.tagName[1:] | tonumber + 1')"
          cd artifacts
          gh release create --latest "$NEXT_TAG" MobileNebula.apk
