name: Build
on: [push]

jobs:
  build:
    name: Build android package
    runs-on: macos-latest

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.5"

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21b
          # r21b is 21.1.6352462, if it is not published here https://developer.android.com/ndk/downloads
          # or here https://github.com/android/ndk/wiki/Unsupported-Downloads then you must download them and look at
          # source.properties to determine the version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get build name and number, install dependencies
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

          flutter pub get

          touch env.sh

      - name: Build Android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          flutter build appbundle --build-number="79" --build-name="0.4.2"

      - name: Collect Android artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MobileNebula.aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 5
