name: Build

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build android package
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.5"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9862592
          packages: "tools platform-tools platforms;android-33"

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21b
          # r21b is 21.1.6352462, if it is not published here https://developer.android.com/ndk/downloads
          # or here https://github.com/android/ndk/wiki/Unsupported-Downloads then you must download them and look at
          # source.properties to determine the version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install the google play key material
        env:
          GOOGLE_PLAY_API_JWT_BASE64: ${{ secrets.GOOGLE_PLAY_API_JWT_BASE64 }}
          GOOGLE_PLAY_KEYSTORE_BASE64: ${{ secrets.GOOGLE_PLAY_KEYSTORE_BASE64 }}
        run: |
          GOOGLE_PLAY_API_JWT_PATH="$RUNNER_TEMP/gp_api.json"
          echo "GOOGLE_PLAY_API_JWT_PATH=$GOOGLE_PLAY_API_JWT_PATH" >> $GITHUB_ENV
          echo -n "$GOOGLE_PLAY_API_JWT_BASE64" | base64 -d > "$GOOGLE_PLAY_API_JWT_PATH"

          GOOGLE_PLAY_KEYSTORE_PATH="$RUNNER_TEMP/gp_signing.jks"
          echo "GOOGLE_PLAY_KEYSTORE_PATH=$GOOGLE_PLAY_KEYSTORE_PATH" >> $GITHUB_ENV
          echo -n "$GOOGLE_PLAY_KEYSTORE_BASE64" | base64 -d > "$GOOGLE_PLAY_KEYSTORE_PATH"

      - name: Get build name and number, install dependencies
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

          flutter pub get

          touch env.sh

      - name: Build Android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          GOOGLE_PLAY_KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_KEYSTORE_PASSWORD }}
        run: |
          flutter build apk

      - name: Collect Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MobileNebula.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5

  release:
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd artifacts
          gh release create \
            --verify-tag \
            --title "Release ${{ github.ref_name }}" \
            "${{ github.ref_name }}" \
            MobileNebula.apk
